market_research:
  description: >
    Conduct a thorough research about {topic} in the space and defense industry.
    Perform market size analysis, growth trends, and customer segmentation.
    Utilize business analysis frameworks such as SWOT, PESTLE, and Porter’s Five Forces
    to evaluate market opportunities and risks.
    Leverage structured and credible data sources including market and industry research reports,
    government and international publications, and business case studies.
    Ensure all insights are data-driven and actionable.
  expected_output: >
    A detailed market research report containing:
      - Overview: Brief summary of the market evaluation and strategic potential.
      - Market Dynamics: Key trends in the space and defense sectors, including demand drivers and market size.
      - Industry Insights: Detailed analysis of technological, financial, and geopolitical factors shaping the market.
      - Strategic Opportunities: Targeted recommendations for partnerships, investments, and market entry strategies.
      - Risk Assessment: Detailed identification and mitigation of risks.
      - Recommendations: Actionable steps to optimize market entry or expansion strategies.
      - Conclusion: High-level summary of findings and strategic next steps.
  agent: market_expert

competitor_analysis:
  description: >
    Conduct a thorough analysis of the competitive landscape for {topic}.
    This includes:
      - Identifying major players and emerging competitors in each target market.
      - Categorizing competitors by scale (global, regional, or local) and assessing their market share.
      - Performing SWOT analysis to evaluate competitors' strengths, weaknesses, opportunities, and threats.
      - Analyzing competitors' product/service offerings, pricing strategies, distribution channels, and customer base.
      - Monitoring competitors' marketing, branding, and promotional strategies.
      - Tracking innovations, technological advancements, and partnerships within the competitive space.
      - Comparing competitors' revenue, growth rate, profitability, and operational efficiency.
      - Benchmarking customer satisfaction and loyalty indicators, if available.
      - Identifying potential threats such as market saturation or price wars.
      - Highlighting gaps or weaknesses in competitors' offerings that the company can exploit.
      - Proposing actionable strategies for differentiation and strategic positioning based on the analysis.
  expected_output: >
    A comprehensive competitor analysis report that includes:
      - Overview: A brief summary of the competitive landscape.
      - Competitor Insights:
          - Detailed findings on each major competitor, including strengths, weaknesses, and strategies.
      - Benchmarking:
          - Comparisons of key performance metrics such as revenue, growth rate, profitability, and operational efficiency.
          - Assessment against industry standards where applicable.
      - Threats and Opportunities:
          - Identification of potential threats posed by competitors.
          - Highlighting exploitable gaps or weaknesses in competitors' offerings.
      - Recommendations:
          - Actionable strategies for differentiation and strategic positioning.
          - Suggestions for leveraging identified opportunities to gain a competitive advantage.
      - Conclusion:
          - High-level summary reinforcing key findings and strategic recommendations.
  agent: competitor_expert

product_analysis:
  description: >
    Evaluate the {company_name} {topic} products for market fit.
    Assess product features, benefits, and performance against market needs.
    Identify target customer segments and analyze how products meet their preferences.
    Conduct competitive differentiation analysis to highlight unique selling propositions.
    Recommend improvements or adaptations to enhance product-market fit.
  expected_output: >
    An in-depth product analysis report containing:
      - Overview: Brief summary of the evaluation of the given product.
      - Product Analysis:
          - Insights into features, benefits, and target customer segments.
      - Market Fit:
          - Assessment of alignment with specific market needs and norms.
      - Competitive Differentiation:
          - Analysis of strengths, gaps, and opportunities.
      - Recommendations:
          - Actionable steps to improve market positioning.
      - Conclusion:
          - High-level summary of findings and next steps.
  agent: product_expert
country_analysis:
  description: >
    Provide localized insights into the economic, regulatory, political, and social factors
    influencing the market entry strategy for {topic} in India, USA, Brazil, and Mexico.
    Analyze economic indicators such as GDP trends, inflation rates, purchasing power, and income distribution for each country.
    Summarize local laws, trade regulations, and compliance requirements relevant to market entry.
    Examine consumer behavior, cultural preferences, and societal norms unique to each market.
    Assess transportation networks, supply chain feasibility, and technology infrastructure.
    Evaluate political stability and identify potential geopolitical risks.
    For countries outside India, USA, Brazil, and Mexico, indicate that the analysis is not aligned with the company's current strategic priorities.
  expected_output: >
    A comprehensive country analysis report that includes:
      - Overview: High-level summary of the market environment in India, USA, Brazil, and Mexico.
      - Key Insights:
          - Economic indicators (GDP trends, inflation rates, purchasing power, income distribution)
          - Regulatory and legal insights (local laws, trade regulations, compliance requirements)
          - Political factors (government priorities, political stability, geopolitical risks)
          - Social and cultural factors (consumer behavior, cultural preferences, societal norms)
          - Infrastructure and logistics assessment (transportation networks, supply chain feasibility, technology infrastructure)
      - Opportunities:
          - Highlight market opportunities based on the analysis for each country.
      - Risks:
          - Identify challenges relevant to market entry in each country.
      - Recommendations:
          - Provide actionable strategies tailored to the company’s goals and market specifics for each country.
      - Conclusion:
          - Summarize the market's fit and feasibility for strategic entry in each country.
      - Non-Aligned Countries:
          - Statement indicating that analysis for countries outside India, USA, Brazil, and Mexico is not available as it does not align with the company's current strategic priorities.
  agent: country_expert

company_analysis:
  description: >
    Conduct a thorough analysis of {company_name}'s internal capabilities, resources, and strategic objectives
    to evaluate readiness for entering the {topic} market. This includes:
      - Assessing strengths, weaknesses, resources, and core competencies.
      - Identifying Unique Selling Propositions (USPs) that differentiate the company.
      - Analyzing organizational structure, financial capacity, and operational scalability.
      - Ensuring that market entry strategies align with the company’s mission, vision, and long-term goals.
      - Evaluating how new opportunities integrate with the existing portfolio and strategic roadmap.
      - Assessing the ability to scale operations, manage supply chains, and meet market-specific requirements.
      - Addressing challenges such as resource limitations, infrastructure gaps, and compliance risks.
      - Proposing mitigation strategies to overcome identified operational challenges.
  expected_output: >
    A comprehensive company analysis report that includes:
      - Overview: A brief summary of the analysis.
      - Key Findings:
          - Evaluation of strengths, weaknesses, resources, and core competencies.
          - Identification of Unique Selling Propositions (USPs).
          - Analysis of organizational structure and financial capacity.
          - Assessment of operational scalability and feasibility.
          - Alignment of market entry strategies with mission and vision.
          - Integration of new opportunities with the existing portfolio.
      - Recommendations:
          - Actionable strategies aligned with the company’s strategic objectives and capabilities.
          - Opportunities for competitive advantage.
      - Risks and Mitigations:
          - Identification of potential challenges.
          - Proposed solutions and mitigation strategies.
      - Conclusion:
          - High-level summary reinforcing strategic fit and feasibility.
  agent: company_expert

reporting_task:
  description: >
    Review all completed analyses and compile them into a comprehensive market entry strategy report for {topic} for {company_name}.
    Ensure the report is well-structured, detailed, and contains all relevant information.
    Include sections on market research, competitor analysis, product analysis, country analysis, and company analysis.
    Present the information in a clear, concise, and actionable manner.
  expected_output: >
    Output Report: Market Entry Strategy for [Product Name]
      - Overview 
        - Executive Summary 
          - Objective: 
          - Product Overview: 
          - Key Insights: 
          - Recommendation: 
        - Product Overview
          - Product Description: 
          - Target Market: 
          - Current Market Presence (only if applicable): 
        - Competitive Landscape
          - Key Competitors: 
          - Market Trends: 
        - Country Recommendations
          - Recommended Country/Multiple Countries:
          - Country Overview: 
          - Reasoning for Recommendation: 
          - Risk Considerations: 
        - SWOT Analysis 
          - Strengths: 
          - Weaknesses: 
          - Opportunities: 
          - Threats: 
        - Financial Considerations
        - Conclusion 
          - Best Market for Entry: 
          - Market Entry Strategy: 
          - Risk Considerations: 
          - Next Steps:
  context:
    [
      market_research,
      competitor_analysis,
      product_analysis,
      country_analysis,
      company_analysis,
    ]
  agent: reporting_analyst
